import { ScanResult } from './scanTypes';

export const demoScanResult: ScanResult = {
  scan_date: '2026-04-28',
  scan_start: '2026-04-28 22:55:00',
  scanned_count: 2103,
  total_stocks: 200,
  top10: [
    {
      stock_id: '3008',
      name: '大立光',
      sector: '光學元件',
      close: 3250,
      change_pct: 3.2,
      total_score: 87.5,
      rsi: 62.4,
      vol_ratio: 2.3,
      dimensions: { technical: 22, chips: 8, fundamental: 32, news: 18, sentiment: 10 },
      signals: {
        technical: ['爆量長紅', '突破月線', 'MACD黃金交叉'],
        chips: ['外資連續買超3天', '融券減少'],
        fundamental: ['PE 15x', '營收成長20%', '毛利率58%'],
        news: ['AI鏡頭題材', '法說會利多'],
        sentiment: ['周轉率放大', '量比2.3x'],
      },
      details: { rsi: 62.4, vol_ratio: 2.3, ma_spread: 2.1, pe: 15.0, gross_margin: 58.0, turnover: 3.8 },
      strategy: { entry: 3200, target: 3500, stop_loss: 3050, upside: 9.4, downside: 4.7, recommendation: '強力買進 - T+3中型部位（+5%出50%，+9%清倉）' },
    },
    {
      stock_id: '2330',
      name: '台積電',
      sector: '半導體',
      close: 895,
      change_pct: 1.7,
      total_score: 83.2,
      rsi: 58.1,
      vol_ratio: 1.9,
      dimensions: { technical: 20, chips: 9, fundamental: 35, news: 12, sentiment: 8 },
      signals: {
        technical: ['均線多頭排列', 'RSI健康(58)', 'KD黃金交叉'],
        chips: ['外資買超5萬張', '投信連買'],
        fundamental: ['PE 22x', '毛利率53%', 'EPS成長35%'],
        news: ['CoWoS擴產題材', '輝達供應鏈'],
        sentiment: ['周轉率健康', '量比1.9x'],
      },
      details: { rsi: 58.1, vol_ratio: 1.9, ma_spread: 1.8, pe: 22.0, gross_margin: 53.0, turnover: 4.2 },
      strategy: { entry: 885, target: 980, stop_loss: 840, upside: 10.7, downside: 5.1, recommendation: '積極買進 - T+5中型部位' },
    },
    {
      stock_id: '2454',
      name: '聯發科',
      sector: '半導體',
      close: 1320,
      change_pct: 2.73,
      total_score: 80.1,
      rsi: 55.3,
      vol_ratio: 1.7,
      dimensions: { technical: 19, chips: 7, fundamental: 30, news: 16, sentiment: 9 },
      signals: {
        technical: ['放量突破季線', '短均線扣抵向上'],
        chips: ['外資回補', '主力加碼'],
        fundamental: ['PE 18x', '毛利率47%'],
        news: ['AI晶片題材', '新品發布'],
        sentiment: ['動能回升', '量比1.7x'],
      },
      details: { rsi: 55.3, vol_ratio: 1.7, ma_spread: 1.5, pe: 18.0, gross_margin: 47.0, turnover: 3.5 },
      strategy: { entry: 1300, target: 1450, stop_loss: 1240, upside: 11.5, downside: 4.6, recommendation: '買進 - T+5小型部位' },
    },
    {
      stock_id: '2382',
      name: '廣達',
      sector: 'AI伺服器',
      close: 298,
      change_pct: 4.15,
      total_score: 78.8,
      rsi: 66.2,
      vol_ratio: 3.1,
      dimensions: { technical: 21, chips: 6, fundamental: 28, news: 17, sentiment: 8 },
      signals: {
        technical: ['爆量創高', '三角收斂突破', '多頭排列'],
        chips: ['外資連買', '法人加碼'],
        fundamental: ['AI伺服器高毛利', 'EPS上修'],
        news: ['GB200組裝', 'AI算力需求爆發'],
        sentiment: ['籌碼集中', '量能放大'],
      },
      details: { rsi: 66.2, vol_ratio: 3.1, ma_spread: 3.2, pe: 16.5, gross_margin: 8.2, turnover: 5.8 },
      strategy: { entry: 292, target: 330, stop_loss: 278, upside: 13.0, downside: 4.8, recommendation: '強力買進 - 短線衝刺部位' },
    },
    {
      stock_id: '2317',
      name: '鴻海',
      sector: 'AI伺服器',
      close: 205,
      change_pct: 2.5,
      total_score: 75.4,
      rsi: 52.8,
      vol_ratio: 1.6,
      dimensions: { technical: 18, chips: 7, fundamental: 27, news: 15, sentiment: 8 },
      signals: {
        technical: ['季線翻揚', '量增價漲', 'MACD上穿零軸'],
        chips: ['外資買超', '融券回補'],
        fundamental: ['AI訂單大幅增加', 'EPS低估'],
        news: ['GB200 ODM唯一供應商', 'BlackWell出貨'],
        sentiment: ['中性偏多', '量比正常'],
      },
      details: { rsi: 52.8, vol_ratio: 1.6, ma_spread: 1.1, pe: 11.2, gross_margin: 6.5, turnover: 3.1 },
      strategy: { entry: 202, target: 225, stop_loss: 193, upside: 11.4, downside: 4.5, recommendation: '買進 - T+5中型部位' },
    },
    {
      stock_id: '6669',
      name: '緯穎',
      sector: 'AI伺服器',
      close: 1580,
      change_pct: 5.33,
      total_score: 74.2,
      rsi: 70.1,
      vol_ratio: 2.8,
      dimensions: { technical: 22, chips: 5, fundamental: 25, news: 14, sentiment: 9 },
      signals: {
        technical: ['強勢噴出', '突破歷史高點', 'RSI超買區'],
        chips: ['主力控盤', '散戶追高'],
        fundamental: ['CSP客戶集中', '高毛利率'],
        news: ['Microsoft AI基礎建設', 'Google GCP採購'],
        sentiment: ['市場追捧', '動能強勁'],
      },
      details: { rsi: 70.1, vol_ratio: 2.8, ma_spread: 4.5, pe: 19.8, gross_margin: 12.1, turnover: 7.2 },
      strategy: { entry: 1560, target: 1750, stop_loss: 1480, upside: 12.2, downside: 5.1, recommendation: '買進 - 小型部位追高需謹慎' },
    },
    {
      stock_id: '2337',
      name: '旺宏',
      sector: '記憶體',
      close: 72.5,
      change_pct: 4.9,
      total_score: 71.6,
      rsi: 61.5,
      vol_ratio: 2.2,
      dimensions: { technical: 19, chips: 6, fundamental: 24, news: 14, sentiment: 8 },
      signals: {
        technical: ['突破盤整區', '量增三倍', '均線多頭'],
        chips: ['外資建倉', '主力加碼'],
        fundamental: ['NOR Flash景氣回升', 'ASP上漲'],
        news: ['車用記憶體需求增加', 'IoT訂單大增'],
        sentiment: ['籌碼換手', '量能健康'],
      },
      details: { rsi: 61.5, vol_ratio: 2.2, ma_spread: 2.8, pe: 14.5, gross_margin: 42.0, turnover: 4.6 },
      strategy: { entry: 71.0, target: 82.0, stop_loss: 67.5, upside: 15.5, downside: 4.9, recommendation: '買進 - T+3中型部位' },
    },
    {
      stock_id: '2308',
      name: '台達電',
      sector: '電源管理',
      close: 385,
      change_pct: 1.85,
      total_score: 69.3,
      rsi: 53.7,
      vol_ratio: 1.5,
      dimensions: { technical: 17, chips: 7, fundamental: 26, news: 12, sentiment: 7 },
      signals: {
        technical: ['月線支撐', '緩步向上', 'MACD多頭'],
        chips: ['法人持續加碼', '外資不賣'],
        fundamental: ['AI電源市佔率高', 'EPS穩健'],
        news: ['GB200電源供應商', 'HVDC市場龍頭'],
        sentiment: ['機構持股增加', '穩健波動'],
      },
      details: { rsi: 53.7, vol_ratio: 1.5, ma_spread: 0.9, pe: 20.3, gross_margin: 29.5, turnover: 2.8 },
      strategy: { entry: 380, target: 420, stop_loss: 362, upside: 10.5, downside: 4.7, recommendation: '買進 - T+5中長線部位' },
    },
    {
      stock_id: '2303',
      name: '聯電',
      sector: '半導體',
      close: 52.8,
      change_pct: 1.15,
      total_score: 65.8,
      rsi: 49.2,
      vol_ratio: 1.3,
      dimensions: { technical: 15, chips: 6, fundamental: 24, news: 12, sentiment: 8 },
      signals: {
        technical: ['底部確認', '量縮整理後放量', '月線翻揚'],
        chips: ['外資低接', '融券持平'],
        fundamental: ['成熟製程需求回穩', 'PE低估'],
        news: ['車用/工控訂單回溫'],
        sentiment: ['低檔籌碼整理', '反彈動能'],
      },
      details: { rsi: 49.2, vol_ratio: 1.3, ma_spread: 0.5, pe: 13.8, gross_margin: 35.2, turnover: 2.2 },
      strategy: { entry: 52.0, target: 60.0, stop_loss: 49.5, upside: 15.4, downside: 4.8, recommendation: '觀望等待訊號確認' },
    },
    {
      stock_id: '2412',
      name: '中華電',
      sector: '電信',
      close: 128.5,
      change_pct: 0.39,
      total_score: 62.1,
      rsi: 47.8,
      vol_ratio: 1.1,
      dimensions: { technical: 14, chips: 5, fundamental: 26, news: 10, sentiment: 7 },
      signals: {
        technical: ['季線附近整理', '低波動', '均線糾結'],
        chips: ['法人小幅加碼', '外資持平'],
        fundamental: ['高殖利率5.5%', '獲利穩定'],
        news: ['5G企業網路佈建', 'FTTB擴張'],
        sentiment: ['防禦性買盤', '低波動'],
      },
      details: { rsi: 47.8, vol_ratio: 1.1, ma_spread: -0.2, pe: 22.5, gross_margin: 48.0, turnover: 1.5 },
      strategy: { entry: 127.5, target: 138.0, stop_loss: 122.0, upside: 8.2, downside: 4.3, recommendation: '觀望 - 適合防禦型部位' },
    },
  ],
};
