#!/usr/bin/env python3
"""
send_intraday_email.py — Send intraday Top 5 picks via Gmail SMTP.
Reads public/data/intraday.json, formats concise HTML email, sends.
"""
import json, os, sys, smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

def normalize_name(name):
    return name.replace("股份有限公司", "").strip()

def load_intraday(path="public/data/intraday.json"):
    p = Path(path)
    if not p.exists():
        print(f"[ERROR] {path} not found")
        sys.exit(1)
    with open(p) as f:
        return json.load(f)

def build_email(data):
    stocks = data.get("stocks", [])[:5]
    scanned_at = data.get("scanned_at", "?")
    scanned_count = data.get("scanned_count", 0)
    qualified_count = data.get("qualified_count", 0)

    rows = ""
    for i, s in enumerate(stocks, 1):
        sid = s.get("stock_id", "?")
        name = normalize_name(s.get("name", "?"))
        score = s.get("score", 0)
        entry = s.get("entry", 0)
        target = s.get("target", 0)
        stop = s.get("stop_loss", 0)
        chg = s.get("change_pct", 0)
        sector = s.get("sector", "?")
        momentum = s.get("details", {}).get("momentum", "?")
        breakout = s.get("details", {}).get("breakout", "?")

        chg_color = "#16a34a" if chg >= 0 else "#dc2626"
        rows += f"""
        <tr>
          <td style="padding:8px 12px;text-align:center;font-weight:700;font-size:16px;color:#111827;">#{i}</td>
          <td style="padding:8px 12px;"><span style="font-weight:600;color:#111827;">{name}</span><br><span style="font-size:11px;color:#6b7280;">{sid} | {sector}</span></td>
          <td style="padding:8px 12px;text-align:center;font-weight:600;color:#0ea5e9;">{score:.1f}</td>
          <td style="padding:8px 12px;text-align:center;font-weight:600;">{entry:.1f}</td>
          <td style="padding:8px 12px;text-align:center;font-weight:600;color:#16a34a;">{target:.1f}</td>
          <td style="padding:8px 12px;text-align:center;font-weight:600;color:#dc2626;">{stop:.1f}</td>
          <td style="padding:8px 12px;text-align:center;font-weight:600;color:{chg_color};">{chg:+.1f}%</td>
          <td style="padding:8px 12px;font-size:12px;color:#6b7280;text-align:center;">{momentum}<br>{breakout}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="zh-TW">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;">
<tr><td align="center" style="padding:24px 16px;">
<table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.1);">

<tr><td style="padding:20px 24px;background:linear-gradient(135deg,#f59e0b,#d97706);">
<div style="font-size:18px;font-weight:700;color:#fff;">Intraday Scan — Top 5 隔日沖</div>
<div style="font-size:12px;color:#fef3c7;margin-top:4px;">{scanned_at} | Scanned {scanned_count} stocks, {qualified_count} qualified</div>
</td></tr>

<tr><td style="padding:4px 0 0;">
<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
<tr style="background:#f9fafb;border-bottom:1px solid #e5e7eb;">
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">#</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;">Stock</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">Score</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">Entry</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">Target</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">Stop</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">Chg%</td>
<td style="padding:8px 12px;font-size:11px;color:#6b7280;text-align:center;">Signal</td>
</tr>
{rows}
</table>
</td></tr>

<tr><td style="padding:12px 24px;border-top:1px solid #e5e7eb;text-align:center;">
<div style="font-size:11px;color:#9ca3af;">
Auto-generated by Taiwan Stock Radar | 隔日沖僅供參考<br>
<a href="https://juststarlight66-oss.github.io/taiwan-stock-radar/intraday" style="color:#0ea5e9;text-decoration:none;">View Dashboard</a>
</div></td></tr>

</table></td></tr></table></body></html>"""
    return html

def send_email(html, scanned_at):
    gmail_user = os.environ.get("GMAIL_USER", "")
    gmail_pass = os.environ.get("GMAIL_APP_PASSWORD", "")
    to_email = os.environ.get("REPORT_TO_EMAIL", gmail_user)

    if not gmail_user or not gmail_pass:
        print("[ERROR] GMAIL_USER or GMAIL_APP_PASSWORD not set")
        sys.exit(1)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[台股雷達] Intraday Top 5 — {scanned_at}"
    msg["From"] = gmail_user
    msg["To"] = to_email
    msg.attach(MIMEText(html, "html", "utf-8"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=30) as s:
        s.login(gmail_user, gmail_pass)
        s.sendmail(gmail_user, [to_email], msg.as_string())
    print(f"[OK] Sent intraday email to {to_email}")

def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "send"
    path = sys.argv[2] if len(sys.argv) > 2 else "public/data/intraday.json"
    data = load_intraday(path)
    stocks = data.get("stocks", [])[:5]
    scanned_at = data.get("scanned_at", "?")
    print(f"[OK] Loaded {len(stocks)} stocks from {path} (scan: {scanned_at})")
    html = build_email(data)
    if mode == "save":
        out = "intraday_email_preview.html"
        with open(out, "w") as f:
            f.write(html)
        print(f"[OK] Preview saved to {out}")
    else:
        send_email(html, scanned_at)

if __name__ == "__main__":
    main()
